# Generated by Django 5.2.5 on 2025-08-10 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_bytes', models.BigIntegerField()),
                ('rx_packets', models.BigIntegerField()),
                ('tx_packets', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_metrics', to='Metrics.device')),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('memory_kb', models.BigIntegerField()),
                ('disk_percent', models.FloatField()),
                ('disk_kb', models.BigIntegerField()),
                ('load_1', models.FloatField()),
                ('load_5', models.FloatField()),
                ('load_15', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_metrics', to='Metrics.device')),
            ],
        ),
    ]
